FROM node:20.12-slim

WORKDIR /app
COPY ./skyvern-frontend/package*.json ./
RUN rm -rf node_modules
RUN npm install

COPY ./skyvern-frontend .
COPY ./entrypoint-skyvernui.sh /app/entrypoint-skyvernui.sh
RUN chmod +x /app/entrypoint-skyvernui.sh

ENV VITE_API_BASE_URL=http://localhost:8000/api/v1
ENV VITE_WSS_BASE_URL=ws://localhost:8000/api/v1
ENV VITE_ARTIFACT_API_BASE_URL=http://localhost:9090

CMD [ "/bin/bash", "/app/entrypoint-skyvernui.sh" ]

